"""Adição da coluna bairro a tabela de ocorrencias

Revision ID: 076c57e1176b
Revises: 94fafd2f5354
Create Date: 2024-09-16 13:40:07.468196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076c57e1176b'
down_revision: Union[str, None] = '94fafd2f5354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocorrencias', sa.Column('bairro', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocorrencias', 'bairro')
    # ### end Alembic commands ###
