"""Make email and cpf unique in Usuario

Revision ID: 6c5765927297
Revises: 33a6f3855cef
Create Date: 2024-11-23 18:04:36.868992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5765927297'
down_revision: Union[str, None] = '33a6f3855cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_usuarios_email", ["email"])
        batch_op.create_unique_constraint("uq_usuarios_cpf", ["cpf"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.drop_constraint("uq_usuarios_email", type_="unique")
        batch_op.drop_constraint("uq_usuarios_cpf", type_="unique")
    # ### end Alembic commands ###
