"""Coordenadas adicionadas a tabela de ocorrencias

Revision ID: 94fafd2f5354
Revises: d5763b8910c0
Create Date: 2024-09-14 11:15:30.900059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fafd2f5354'
down_revision: Union[str, None] = 'd5763b8910c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocorrencias', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('ocorrencias', sa.Column('longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocorrencias', 'longitude')
    op.drop_column('ocorrencias', 'latitude')
    # ### end Alembic commands ###
