"""versão inicial dos modelos finalizada

Revision ID: d5763b8910c0
Revises: 
Create Date: 2024-09-13 19:38:31.225172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5763b8910c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('cidadaos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('num_ocorrencias_registradas', sa.Integer(), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('funcionarios_defesa_civil',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('nivel_acesso', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ocorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('ultima_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocorrencias_id'), 'ocorrencias', ['id'], unique=False)
    op.create_table('curtidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('oc_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['oc_id'], ['ocorrencias.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curtidas_id'), 'curtidas', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('oc_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['oc_id'], ['ocorrencias.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_table('midias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oc_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('caminho', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['oc_id'], ['ocorrencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_midias_id'), 'midias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_midias_id'), table_name='midias')
    op.drop_table('midias')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_curtidas_id'), table_name='curtidas')
    op.drop_table('curtidas')
    op.drop_index(op.f('ix_ocorrencias_id'), table_name='ocorrencias')
    op.drop_table('ocorrencias')
    op.drop_table('funcionarios_defesa_civil')
    op.drop_table('cidadaos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
